name = "Мухамедов Отабек Фарходжон угли"
description = "Менеджер по продажам (по развитию дилеров)"
keywords = ""
image = "photo_2025-05-14_09-25-13.webp"
theme = "light"
primary_color = "#292c35"
text_align = "center"
gtag_id = ""
base_url = "https://biloliddinabdujalilov.github.io/otabek/"

[[sections]]
title = "Контакты"
description = "+998 99 873 63 93 | +998 55 508 60 60"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/tzYdqMRJntk?si=3yLTORA7CZQMXh33"
[[sections.items]]
title = "Telegram"
description = "@mukhamedov6393"
url = "https://t.me/mukhamedov6393"
[[sections.items]]
title = "WhatsApp"
description = "+998 99 873 63 93"
url = "https://wa.me/998998736393"
[[sections.items]]
title = "E-mail"
description = "mukhamedovotabek6393@gmail.com"
url = "mailto:mukhamedovotabek6393@gmail.com"


[[sections]]
title = "Ссылки"
description = "Социальные сети компании VUM"
direction = "row"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram"
title = "Instagram"
url = "https://www.instagram.com/vum_faw_uzbekistan"
[[sections.items]]
icon = "https://cdn.simpleicons.org/youtube"
title = "YouTube"
url = "https://www.youtube.com/@faw_uzbekistan/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/google"
title = "Сайт"
url = "https://faw.uz"
[[sections.items]]
title = "Facebook"
icon = "https://cdn.simpleicons.org/facebook"
url = "https://www.facebook.com/fawuzbekistan"
